-- MySQL Script generated by MySQL Workbench
-- Mon Sep 23 11:52:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pdi_2024
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pdi_2024` ;

-- -----------------------------------------------------
-- Schema pdi_2024
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pdi_2024` DEFAULT CHARACTER SET utf8 ;
USE `pdi_2024` ;

-- -----------------------------------------------------
-- Table `pdi_2024`.`type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pdi_2024`.`type` ;

CREATE TABLE IF NOT EXISTS `pdi_2024`.`type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pdi_2024`.`funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pdi_2024`.`funcionario` ;

CREATE TABLE IF NOT EXISTS `pdi_2024`.`funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(200) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(200) NULL,
  `cargo` VARCHAR(45) NULL,
  `status` INT NULL,
  `gestor_id` INT(11) NULL,
  `type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_funcionario_type1_idx` (`type_id` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_type1`
    FOREIGN KEY (`type_id`)
    REFERENCES `pdi_2024`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pdi_2024`.`questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pdi_2024`.`questions` ;

CREATE TABLE IF NOT EXISTS `pdi_2024`.`questions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numquestion` INT NULL,
  `question` MEDIUMTEXT NULL,
  `detailquestion` MEDIUMTEXT NULL,
  `type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_questions_type1_idx` (`type_id` ASC) VISIBLE,
  CONSTRAINT `fk_questions_type1`
    FOREIGN KEY (`type_id`)
    REFERENCES `pdi_2024`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pdi_2024`.`options`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pdi_2024`.`options` ;

CREATE TABLE IF NOT EXISTS `pdi_2024`.`options` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numoption` INT NULL,
  `option` MEDIUMTEXT NULL,
  `questions_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_options_questions_idx` (`questions_id` ASC) VISIBLE,
  CONSTRAINT `fk_options_questions`
    FOREIGN KEY (`questions_id`)
    REFERENCES `pdi_2024`.`questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pdi_2024`.`avaliacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pdi_2024`.`avaliacao` ;

CREATE TABLE IF NOT EXISTS `pdi_2024`.`avaliacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` INT NULL,
  `options_id` INT NOT NULL,
  `funcionario_id` INT NOT NULL,
  `funcionario_id_avaliador` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_avaliacaoliderado_options1_idx` (`options_id` ASC) VISIBLE,
  INDEX `fk_avaliacao_funcionario1_idx` (`funcionario_id` ASC) VISIBLE,
  INDEX `fk_avaliacao_funcionario2_idx` (`funcionario_id_avaliador` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacaoliderado_options1`
    FOREIGN KEY (`options_id`)
    REFERENCES `pdi_2024`.`options` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_funcionario1`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `pdi_2024`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_funcionario2`
    FOREIGN KEY (`funcionario_id_avaliador`)
    REFERENCES `pdi_2024`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pdi_2024`.`avaliador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pdi_2024`.`avaliador` ;

CREATE TABLE IF NOT EXISTS `pdi_2024`.`avaliador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `funcionario_id` INT NOT NULL,
  `funcionario_id_avaliador` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_avaliador_funcionario1_idx` (`funcionario_id` ASC) VISIBLE,
  INDEX `fk_avaliador_funcionario2_idx` (`funcionario_id_avaliador` ASC) VISIBLE,
  CONSTRAINT `fk_avaliador_funcionario1`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `pdi_2024`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliador_funcionario2`
    FOREIGN KEY (`funcionario_id_avaliador`)
    REFERENCES `pdi_2024`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
